[package]
name = "editor"
version = "0.1.0"
authors = ["mtwtkman <punipuniomochi@gmail.com>"]

[dependencies]
hyper = "*"
iron = "*"
router = "*"
staticfile = "*"
diesel = "0.9.0"
handlebars-iron = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[features]
watch = ["handlebars-iron/watch"]
