[package]
name = "editor"
version = "0.1.0"
authors = ["root"]

[dependencies]
iron = "*"
tera = "*"
router = "*"
iron-tera = { path = "iron-tera" }
handlebars-iron = "*"
handlebars = "*"
serde_json = "*"
