[package]
name = "editor"
version = "0.1.0"
authors = ["mtwtkman"]

[dependencies]
iron = "^0.5"
router = "^0.5"
iron-test = "^0.5"
serde = "^0.9"
serde_yaml = "^0.6"
serde_derive = "^0.9"
serde_json = "^0.9"
